// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuikyEcB-6GfAnfpZSFIECZJtBunJIag0',
    appId: '1:970463515163:web:94f67fe4fd0d5870bedebe',
    messagingSenderId: '970463515163',
    projectId: 'my-wallet-app-41e6b',
    authDomain: 'my-wallet-app-41e6b.firebaseapp.com',
    storageBucket: 'my-wallet-app-41e6b.appspot.com',
    measurementId: 'G-FRKGWC7ZQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh7usMRx98FXTB5W5Me5Al8V_fjmJi4_0',
    appId: '1:970463515163:android:ac2b23bf7a1c666cbedebe',
    messagingSenderId: '970463515163',
    projectId: 'my-wallet-app-41e6b',
    storageBucket: 'my-wallet-app-41e6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBx9mVH_w_-fqJT55oLuXB414zLoD9OPk',
    appId: '1:970463515163:ios:110a83ea40000df1bedebe',
    messagingSenderId: '970463515163',
    projectId: 'my-wallet-app-41e6b',
    storageBucket: 'my-wallet-app-41e6b.appspot.com',
    iosClientId: '970463515163-7fi71i50t7vkn2ugrqtik451ott6j7oe.apps.googleusercontent.com',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBx9mVH_w_-fqJT55oLuXB414zLoD9OPk',
    appId: '1:970463515163:ios:b89141742cc8a0febedebe',
    messagingSenderId: '970463515163',
    projectId: 'my-wallet-app-41e6b',
    storageBucket: 'my-wallet-app-41e6b.appspot.com',
    iosClientId: '970463515163-jgo2cki19ea5si57ala3618n8ffo0t6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.newApp.RunnerTests',
  );
}
